version: "2"
services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
  django-web-app:
    image: "farix44/django_web_app"
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "django-insecure-@z_9m*&7cmft(87^j1(b6%0uddzvc$$0s!@1mgop*1rrtfzx(nz"
      DATABASE_NAME: "web_app_postgresql_db"
      DATABASE_USER: "marcin"
      DATABASE_PASS: "Marcin1!"
      DATABASE_HOST: "postgres"
      CORS_ALLOWED_ORIGINS: "http://django-web-app:8000"
      CORS_ALLOWED_ORIGIN_REGEXES: "http://django-web-app:8000"
      ALLOWED_HOSTS: "*"
      DJANGO_SUPERUSER_PASSWORD: "admin"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: ""
#    command: sh -c "/usr/src/presetup-api.sh"
    depends_on:
      - postgres
  django-kredyty-html:
    image: "farix44/django_kredyty_html"
    ports:
      - "80:80"
    depends_on:
      - django-web-app
