# Generated by Django 3.2.4 on 2021-08-20 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('amount', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(10000)])),
                ('period', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ('interest_rate', models.FloatField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(8)])),
                ('repayment_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
