# Generated by Django 3.2.4 on 2021-06-22 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredyty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wnioski',
            name='kredytobiorca',
            field=models.CharField(default='Klient', max_length=64),
        ),
        migrations.AlterField(
            model_name='wnioski',
            name='kwota',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='wnioski',
            name='okres',
            field=models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)]),
        ),
    ]
