# Generated by Django 3.2.4 on 2021-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredyty', '0002_auto_20210622_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wnioski',
            name='kredytobiorca',
            field=models.CharField(max_length=64),
        ),
    ]
