# Generated by Django 3.2.4 on 2021-07-09 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredyty', '0003_alter_wnioski_kredytobiorca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wnioski',
            name='kwota',
            field=models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
