# Generated by Django 3.2.4 on 2021-07-15 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredyty', '0005_auto_20210709_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=64)),
                ('nazwisko', models.CharField(max_length=64)),
                ('kwota', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(10000)])),
                ('okres', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ('oprocentowanie', models.FloatField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.DeleteModel(
            name='Wnioski',
        ),
    ]
