# Generated by Django 3.2.4 on 2021-07-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kredyty', '0006_auto_20210715_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='kwota',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='imie',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='oprocentowanie',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='okres',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='nazwisko',
            new_name='second_name',
        ),
    ]
