# Generated by Django 3.2.4 on 2021-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredyty', '0007_auto_20210715_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='repayment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
