# Generated by Django 3.2.4 on 2021-08-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredyty', '0009_alter_loans_repayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='repayment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
